---

- name: Check if ntp is installed
  apt:
    name: ntp
    state: present
  tags: ntp

- name: Check if ntp is configured
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: 
    - restart ntp
  tags: ntp

- name: Ensure ntp is running
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
